### ISSUE TITLE
Verify behaviour of 'ManifestDidLoad' event

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/diva.js#357] opened 2016-08-24 15:58 UTC
This event is triggered before the IIIF manifest has been parsed:
https://github.com/DDMAL/diva.js/blob/develop/source/js/diva.js#L354
Is that the intended behaviour?

Furthermore, this event seems to only be triggered when a IIIF manifest is loaded. It is used by the iiif-highlight and iiif-metadata plugins, so my guess is that those would break if this event triggered when a IIP manifest would load.
This probably does not really matter if support for IIP manifests is going away in Diva 6 anyway.

Refs #355

**Comment by ahankinson** [comment] 2016-08-24 16:00
Would it make sense if this was `ManifestWillLoad`?

**Comment by jeromepl** [comment] 2016-08-24 16:05
It would, but I don't see any use case of a `ManifestWillLoad` event. It seems like you would want to do something only after the manifest has loaded, since you already know the manifest will load once you instantiate Diva.

**Comment by ahankinson** [comment] 2016-08-24 16:12
Usually `Will` and `Did` are fired in pairs before and after an action. They give systems the opportunity to hook in to the process. If, for example, you wanted to change a manifest **prior** to its parsing in Diva, you might do that at the `Will` stage.

**Comment by jeromepl** [comment] 2016-08-24 16:14
Yes, what I am saying is this event would seem to make more sense if it was fired **after** the manifest has been parsed. In that case it would still be called `ManifestDidLoad`.

**Comment by ahankinson** [comment] 2016-08-24 16:14
Looking at it, it may be that 'load' is defined as after the manifest has been fetched and before it has been parsed. I suspect this particular function is used as the callback from the ajax request, so once it has returned the manifest has 'loaded'.

**Comment by ahankinson** [comment] 2016-08-24 21:47
I don't see this event in the [list of events in the documentation](https://github.com/DDMAL/diva.js/wiki/Events-System) Could you double-check this and add it?

**Comment by jeromepl** [comment] 2016-08-24 22:11
I am currently going through all the pages in the Wiki. Everything starting from the Events page, going down, will be done tomorrow morning! I will make sure to add this event.

**Comment by jeromepl** [comment] 2016-08-25 18:55
https://github.com/DDMAL/diva.js/wiki/Events-System#manifestdidload-manifest

**Comment by EricHanLiu** [comment] 2018-07-30 16:45
Makes sense that the event is triggered before parsing, but after the responseData is received. IIP manifest support has been removed. Closing this issue since this seems to be the intended behaviour.

**Closed by EricHanLiu** 2018-07-30 16:45 UTC
Labels: Component: Core, Type: Code maintenance / Tests
