### ISSUE TITLE
disableScrollable() gives an error

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/diva.js#389] opened 2017-05-23 18:57 UTC
The error message is as follows:

```
Uncaught TypeError: this.viewerState.innerObject.hasClass is not a function
    at ViewerCore.disableScrollable (viewer-core.js:1401)
    at PixelPlugin.activatePlugin (pixel.js:88)
    at PixelPlugin.handleClick (pixel.js:321)
    at HTMLDivElement.<anonymous> (page-tools-overlay.js:53)
```

**Comment by PotassiumK** [comment] 2017-06-08 19:03
Duplicate of #392

**Closed by PotassiumK** 2017-06-08 19:03 UTC
Labels: Component: Core, Priority: High, Type: Bug
