### ISSUE TITLE
Jumping to a page will not render it

### ISSUE THREAD

**Issue by wagnerflo** [DDMAL/diva.js#390] opened 2017-05-29 08:45 UTC
I'm currently trying out diva.js and building a mockup to evaluate it. I've noticed the following problem, which I can reproduce with my mockup as well as with the IIIF example (http://ddmal.github.io/diva.js/try/demo/iiif-external.html) but interestingly not with the Cantus Ultimus (https://cantus.simssa.ca/manuscript/133/).

Anytime I jump to a page, either by using the "Go to" toolbar or from a custom Javascript using the `gotoPageByIndex` function diva will jump to the right offset it in canvas view but will not display any tiles at all. It will just show the images frame but anything else will be of the canvas' background color. As soon as I scroll within the canvas (mouse wheel or scrollbar) the images appear at once.

My browser (Firefox 53.0.3 on Linux) logs multiple IndexSizeError.

See also attached screenshot.

![diva js_problem](https://cloud.githubusercontent.com/assets/6588666/26542857/c8de7a3c-445b-11e7-8aee-75498968892b.jpg)

**Comment by wagnerflo** [comment] 2017-06-01 08:10
Had time to do bit of digging and found a page about this on [Stackoverflow](https://stackoverflow.com/questions/19338032/canvas-indexsizeerror-index-or-size-is-negative-or-greater-than-the-allowed-a).

In addition to the solution presented in that article (`Math.max(1, w); ...`) what also works is wrapping the `this._ctx.drawImage` call at [source/js/renderer.js line 381](https://github.com/DDMAL/diva.js/blob/v5.1.2/source/js/renderer.js#L381) in a `if (sourceWidth > 0 && sourceHeight > 0)`.

I have absolutely no idea what I'm doing here and if this is even remotely the right way to fix this problem.

**Comment by ahankinson** [comment] 2017-06-01 08:52
Hi @wagnerflo, yeah I had a chance to dig through it and didn't get very far. I'll see if I can patch this up and do a new release. Thanks for your patience.

**Comment by ahankinson** [comment] 2017-06-01 12:06
I've committed a fix for this to the develop branch. Thank you so much for digging out the cause.

If you can verify that it works for you, I'll make a new release and distribute it to NPM

**Comment by wagnerflo** [comment] 2017-06-01 14:33
I've manually made changes equivalent to your commit in my copy of `build/js/diva.js` and can confirm that the reported error is gone that way, too.

**Closed** 2017-06-05 08:14 UTC
