### ISSUE TITLE
Problems with scrollbars

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#446] opened 2018-08-18 00:53 UTC
- On safari, the bottom scrollbar appears. This should be hidden.
 - On chrome, the vertical scrollbar doesn't appear (but this may be just my computer?)

Check and verify proper scrollbar functions and appearance.

**Comment by EricHanLiu** [comment] 2018-08-20 13:27
I can't replicate this issue. 

In safari for me, the vertical scrollbar doesn't appear (within `diva-inner`), but I don't see the bottom scrollbar.

I have no issues in chrome

**Comment by EricHanLiu** [comment] 2018-08-20 13:37
Still no bottom scrollbar in either, tried it with a larger window as well (two screens). 

Can't reproduce this issue and i'm guessing it's related to #441 (whose feature is being stalled for now), closing.

**Closed by EricHanLiu** 2018-08-20 13:37 UTC
Labels: Component: UI, Priority: High, Type: Bug
