### ISSUE TITLE
Sharpness filter breaks

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#445] opened 2018-08-18 00:18 UTC
Adjusting the sharpness filter does not seem to work and produces this error:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/163183/44293585-7bba7480-a284-11e8-8ff3-a06e2acca89f.png">

**Comment by EricHanLiu** [comment] 2018-08-20 17:54
I can't reproduce this issue, not with a large screen, chrome, safari, or firefox.

Perhaps this was thrown when the image hadn't been selected yet? Then none of the filters would've worked.

How did you come about this issue?

**Comment by EricHanLiu** [comment] 2018-08-20 18:00
Seems like this was never an issue or it was fixed in the meantime. Closing until a reproducible case can be given

**Comment by ahankinson** [comment] 2018-08-21 12:26
It's still broken for me.

**Comment by ahankinson** [comment] 2018-08-21 12:28
Open manipulation filter, select image, wait for it to load in centre, select any value on the 'sharpness' scale, get an error in the console. I'm on Chrome 68.0.3440.106

**Comment by ahankinson** [comment] 2018-08-21 12:31
New data point: If I run it with the 'develop' plugin, it works fine. If I run it with the 'production' one, it errors.

`npm run build:develop` : fine
`npm run build:production` : sad-face

**Comment by EricHanLiu** [comment] 2018-08-21 14:25
It seems the issue is in production mode, the `filterObject.filterFunction.name` isn't returning convolve, but instead C, since the file is minified (I'm assuming). Will need to do a different check for the function name

**Closed** 2018-08-21 14:48 UTC
